[project]
name = "aws-primer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dinu Gherman", email = "gherman@darwin.in-berlin.de" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
aws-primer = "aws_primer:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
